"Parameter" "Value" "Units" "Description" "LaTeX"
"alpha" "3    " "g s MPa mmol^-1 d^-1  " "photsynthetic rate per stomatal conductance       " "$\\alpha$"
"beta " "0.5  " "g g^-1 d^-1           " "repair coefficient                                " "$\\beta$ "
"gamma" "0    " "g g-1 d-1             " "growth coefficient                                " "$\\gamma$"
"theta" "0.075" "mmol s-1 MPa-1 d-1 g-1" "repair efficacy                                   " "$\\theta$"
"kmax " "10   " "mmol s-1 MPa-1        " "maximum hydraulic contuctance                     " "$k_{max}$  "
"m    " "0    " "g d-1                 " "minimum maintenance respiration carb allocation   " "$m$        "
"l.B  " "1    " "                      " "scale parameter for growth weibull function       " "$l_B$      "
"k.B  " "1    " "                      " "shape parameter for growth weibull function       " "$k_B$      "
"l.K  " "0.45 " "                      " "scale parameter for conductance weibull function  " "$l_K$      "
"k.K  " "3.85 " "                      " "shape paramter for conductance weibull function   " "$k_K$      "
"G.min" "0.05 " "mmol s-1 MPa-1        " "minimum stomatal conductance                      " "$G_{min}$  "
"h    " "1    " "m                     " "tree height                                       " "$h$        "
"rho  " "1    " "g cm^-3               " "density of water                                  " "$\\rho$  "
"g    " "1    " "m s^-2                " "accelleration of gravity                          " "$g$        "
"zeta " "1    " "                      " "stomatal sensitivity to ABA                       " "$\\zeta$ "
"omega" "1    " "                      " "range of stomatal opening                         " "$\\omega$"
"tau  " "0.95 " "                      " "stomatal sensitivity to leaf water potential      " "$\\tau$  "
"a    " "0.1  " "                      " "ABA production sensitivity to soil water potential" "$a$        "
"b    " "5    " "                      " "ABA consumption rate                              " "$b$        "
"State" "Value" "Units                 " "Description                                       " "LaTeX      "
"Psi_s" "-4   " "MPa                   " "soil water potential                              " "$\\Psi_s$"
"D    " "4    " "MPa                   " "leaf surface moisture saturation deficit          " "$D$        "
"S    " "1    " "g                     " "total non-structural carbohydrates                " "$S$        "
"K    " "10   " "mmol s^-1 MPa^-1      " "xylem conductance                                 " "$K$        "
